### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by Stan-ciu** [codecatchllc/cpu-temp-prometheus-exporter#1]
Trying to get this to work, when checking if the service is working... I'm getting failed.

**Comment by AustinLeath** [comment]
Hello @Albastruu, can I have a little more information about your issue?

Please provide the following information:

1. Provide the contents of your systemd file 
2. Provide the output of `systemctl status cpu-exporter.service`
3. Check `journalctl -xef` for any errors with the service and report them here
4. Provide any screenshots

**Comment by Stan-ciu** [comment]
This has been resolved.

Thanks for the quick response.

@AustinLeath

**Comment by AustinLeath** [comment]
No problem! Closing this issue out
